const mongoose = require("mongoose");
const dotenv = require("dotenv");
dotenv.config();

const Organ = require("./models/Organ");
const Disease = require("./models/Disease");

const organs = [
  {
    name: "Brain",
    slug: "brain",
    system: "Nervous System",
    location: "Inside the skull (cranium)",
    weight: "1.4 kg",
    color: "#E8C5A0",
    shortDesc: "The command center of the human body, processing sensory input and coordinating behavior.",
    overview: "The human brain is the most complex organ in the known universe, containing approximately 86 billion neurons. It consumes 20% of the body's total energy despite accounting for only 2% of body weight.",
    description: "The command center of the human body, processing sensory input and coordinating behavior.",
    parts: [
      {
        name: "Cerebrum",
        biologicalTerm: "Telencephalon",
        description: "Largest part of the brain. Responsible for higher cognitive functions, conscious thought, reasoning, and voluntary actions.",
        location: "Upper region of the brain.",
        functions: ["Thinking", "Memory", "Learning", "Speech", "Voluntary Movements"],
        additionalFacts: "Accounts for about 85% of the brain's total weight.",
        color: "#D4956A",
      },
      {
        name: "Cerebellum",
        biologicalTerm: "Metencephalon (Cerebellum)",
        description: "Coordinates voluntary movements, posture, motor learning, and fine-tuned balance.",
        location: "Lower back of the brain.",
        functions: ["Balance", "Coordination", "Posture", "Fine motor control"],
        additionalFacts: "Contains more neurons than the rest of the brain combined.",
        color: "#C97B54",
      },
      {
        name: "Thalamus",
        biologicalTerm: "Diencephalon (Thalamus)",
        description: "Acts as the brain's sensory relay station, routing incoming signals from sensory organs to the cerebral cortex.",
        location: "Deep central region of the brain.",
        functions: ["Relaying sensory information", "Sleep/wake regulation", "Alertness"],
        additionalFacts: "Every sense except smell passes through the thalamus before reaching the cortex.",
        color: "#E0A882",
      },
      {
        name: "Hypothalamus",
        biologicalTerm: "Diencephalon (Hypothalamus)",
        description: "Maintains homeostasis by regulating core temperature, thirst, hunger, circadian rhythms, and endocrine hormone release.",
        location: "Below the thalamus, near the brain stem.",
        functions: ["Regulating body temperature", "Hunger and thirst", "Hormone control", "Circadian rhythms"],
        additionalFacts: "Links the nervous system directly to the endocrine system via the pituitary gland.",
        color: "#BF7D5A",
      },
      {
        name: "Brain Stem",
        biologicalTerm: "Truncus Encephali",
        description: "Connects the brain to the spinal cord and autonomously controls vital life-support functions like breathing and heart rate.",
        location: "Base of the brain connecting to the spinal cord.",
        functions: ["Breathing", "Heart rate", "Blood pressure", "Swallowing", "Cough reflex"],
        additionalFacts: "Controls vital involuntary functions essential for survival.",
        color: "#A85D38",
      },
      {
        name: "Pituitary Gland",
        biologicalTerm: "Hypophysis",
        description: "The 'master gland' that synthesizes and secretes critical hormones governing growth, thyroid activity, and adrenal response.",
        location: "Base of the brain, below the hypothalamus.",
        functions: ["Hormone production", "Growth regulation", "Metabolism control", "Reproductive regulation"],
        additionalFacts: "Pea-sized gland resting securely inside the sella turcica of the sphenoid bone.",
        color: "#9E6245",
      },
    ],
    diseases: ["Alzheimer's Disease", "Parkinson's Disease", "Stroke", "Epilepsy"],
    funFacts: [
      "Your brain generates about 23 watts of electrical power — enough to illuminate a small light bulb.",
      "The brain has no pain receptors; brain tissue itself cannot feel pain.",
      "Information can travel along nerve pathways at speeds up to 120 meters per second.",
    ],
    biomimicry: {
      inspiration: "Microprocessors & Artificial Neural Networks",
      explanation: "Layered memory storage and massively parallel neuron architectures inspired computer cache hierarchies and deep learning artificial neural networks.",
      module: "Neuro-Computing",
    },
    relatedOrgans: ["spinal-cord", "eye", "ear"],
  },
  {
    name: "Heart",
    slug: "heart",
    system: "Cardiovascular System",
    location: "Centre of chest, slightly left of sternum",
    weight: "300 g",
    color: "#C0392B",
    shortDesc: "The muscular pump that beats 100,000 times a day, circulating 5 liters of blood every minute.",
    overview: "The heart is a hollow muscular organ that pumps oxygenated blood to body tissues and deoxygenated blood to the lungs.",
    description: "The muscular organ that pumps blood continuously throughout the circulatory system.",
    parts: [
      {
        name: "Left Atrium",
        biologicalTerm: "Atrium Sinistrum",
        description: "Upper left chamber receiving freshly oxygenated blood from the lungs via pulmonary veins.",
        location: "Upper left chamber.",
        functions: ["Receives oxygenated blood from lungs", "Pumps blood to left ventricle"],
        additionalFacts: "Operates under low filling pressure.",
        color: "#E57373",
      },
      {
        name: "Right Atrium",
        biologicalTerm: "Atrium Dextrum",
        description: "Upper right chamber receiving deoxygenated blood returning from bodily systemic tissues via the vena cava.",
        location: "Upper right chamber.",
        functions: ["Receives deoxygenated blood from the body", "Pumps blood into right ventricle"],
        additionalFacts: "Contains the Sinoatrial (SA) node, the natural biological pacemaker.",
        color: "#EF9A9A",
      },
      {
        name: "Left Ventricle",
        biologicalTerm: "Ventriculus Sinister",
        description: "Thickest muscular chamber responsible for pumping oxygenated blood into the aorta against systemic vascular resistance.",
        location: "Lower left chamber.",
        functions: ["Pumps oxygenated blood to the entire body", "Maintains systemic systolic blood pressure"],
        additionalFacts: "Its myocardium is roughly three times thicker than the right ventricle.",
        color: "#E74C3C",
      },
      {
        name: "Right Ventricle",
        biologicalTerm: "Ventriculus Dexter",
        description: "Lower right chamber pumping venous deoxygenated blood into the pulmonary artery toward the pulmonary capillary bed.",
        location: "Lower right chamber.",
        functions: ["Pumps deoxygenated blood to lungs", "Maintains low-pressure pulmonary circulation"],
        additionalFacts: "Operates at approximately 1/5th the pressure of the systemic left ventricle.",
        color: "#C0392B",
      },
      {
        name: "Aorta",
        biologicalTerm: "Aorta",
        description: "The largest systemic artery in the body, branching out to deliver oxygen-rich blood to all organs and limbs.",
        location: "Emerges from the left ventricle.",
        functions: ["Distributes oxygenated blood to body", "Absorbs systolic impulse via elastic recoil"],
        additionalFacts: "Can withstand pressure swings up to 200 mmHg in healthy adults.",
        color: "#D32F2F",
      },
      {
        name: "Pulmonary Artery",
        biologicalTerm: "Truncus Pulmonalis",
        description: "The unique artery that channels deoxygenated blood away from the right ventricle into both lungs.",
        location: "Emerges from the right ventricle.",
        functions: ["Carries deoxygenated blood to the lungs for gas exchange"],
        additionalFacts: "The only artery in postnatal humans that transports oxygen-depleted blood.",
        color: "#B71C1C",
      },
    ],
    diseases: ["Heart Attack", "Coronary Artery Disease", "Arrhythmia", "Heart Failure"],
    funFacts: [
      "The heart beats approximately 100,000 times a day — over 2.5 billion times in an average lifetime.",
      "The heart has its own electrical conduction system and can beat even outside the body if supplied with oxygen.",
    ],
    biomimicry: {
      inspiration: "Hydraulic Pumps & One-Way Check Valves",
      explanation: "The heart's four-chamber cyclical displacement and flexible one-way valves inspired modern industrial fluid pumps and artificial ventricular assist devices.",
      module: "Fluid Dynamics",
    },
    relatedOrgans: ["lungs", "kidney", "liver"],
  },
  {
    name: "Lungs",
    slug: "lungs",
    system: "Respiratory System",
    location: "Inside the thoracic cavity, flanking the heart",
    weight: "1.3 kg total",
    color: "#E91E63",
    shortDesc: "Primary organs of respiration that bring in oxygen and expel carbon dioxide across 300 million alveoli.",
    overview: "The lungs facilitate gas exchange between inhaled atmospheric air and the circulatory system across a massive surface area equivalent to a tennis court.",
    description: "Primary organs of respiration, facilitating vital gas exchange.",
    parts: [
      {
        name: "Trachea",
        biologicalTerm: "Trachea",
        description: "The cartilaginous windpipe providing an unobstructed conduit for air passing between larynx and bronchi.",
        location: "Front of neck down into superior mediastinum.",
        functions: ["Passes air to bronchi", "Ciliary mucosal filtration and warming of incoming air"],
        additionalFacts: "Maintained patent by 16 to 20 C-shaped rings of hyaline cartilage.",
        color: "#F48FB1",
      },
      {
        name: "Bronchi",
        biologicalTerm: "Bronchus",
        description: "The primary airway bifurcations branching from the trachea into the left and right pulmonary lobes.",
        location: "Upper lung entrance at the pulmonary hilum.",
        functions: ["Conducts air into each lung lobe", "Further warms and humidifies air"],
        additionalFacts: "The right primary bronchus is wider and more vertical than the left.",
        color: "#E91E63",
      },
      {
        name: "Bronchioles",
        biologicalTerm: "Bronchioli",
        description: "Narrow microscopic airway branches terminating at the alveolar sacs, regulated by smooth muscle tone.",
        location: "Throughout lung parenchyma.",
        functions: ["Regulates airway resistance", "Channels air into alveolar clusters"],
        additionalFacts: "Lack cartilage rings, making them susceptible to bronchoconstriction during asthma.",
        color: "#C2185B",
      },
      {
        name: "Alveoli",
        biologicalTerm: "Alveoli Pulmonis",
        description: "Microscopic elastic sacs where passive diffusion of oxygen into erythrocytes and carbon dioxide out occurs.",
        location: "Microscopic terminals of respiratory bronchioles.",
        functions: ["Site of O2 and CO2 gas exchange", "Secretes surfactant to reduce surface tension"],
        additionalFacts: "Both lungs contain approximately 300 to 500 million individual alveoli.",
        color: "#F06292",
      },
    ],
    diseases: ["Asthma", "Pneumonia", "COPD", "Lung Cancer"],
    funFacts: [
      "The total surface area of all alveoli combined is approximately 70-100 square meters.",
      "The right lung has three lobes, while the left lung has only two to leave room for the cardiac notch.",
    ],
    biomimicry: {
      inspiration: "HEPA Filters & Gas Separation Membranes",
      explanation: "The branching fractal network and ultra-thin alveolar diffusion barrier inspired industrial gas separation and HEPA filtration membranes.",
      module: "Membrane Tech",
    },
    relatedOrgans: ["heart", "brain"],
  },
  {
    name: "Digestive System",
    slug: "digestive-system",
    system: "Digestive System",
    location: "Extends from oral cavity through thoracic and abdominopelvic cavities",
    weight: "~5 kg total",
    color: "#E74C3C",
    shortDesc: "A 30-foot biochemical processing tract that mechanically and enzymatically breaks down food for nutrient absorption.",
    overview: "The digestive system breaks down food macromolecules into bioavailable amino acids, simple sugars, and fatty acids.",
    description: "Breaks down food and absorbs nutrients to power the human body.",
    parts: [
      {
        name: "Mouth",
        biologicalTerm: "Cavitas Oris",
        description: "The entryway for ingestion where mastication and salivary amylase begin mechanical and chemical digestion.",
        location: "Facial cavity.",
        functions: ["Ingestion", "Mechanical mastication", "Enzymatic breakdown of starches"],
        additionalFacts: "Produces between 1 and 1.5 liters of saliva daily.",
        color: "#EC7063",
      },
      {
        name: "Esophagus",
        biologicalTerm: "Oesophagus",
        description: "Muscular peristaltic tube conveying food boluses smoothly from the pharynx down to the gastric cardia.",
        location: "Posterior mediastinum connecting throat to stomach.",
        functions: ["Transports food via synchronized peristaltic waves"],
        additionalFacts: "Contains both striated muscle in the upper third and smooth muscle in the lower third.",
        color: "#F1948A",
      },
      {
        name: "Stomach",
        biologicalTerm: "Gaster",
        description: "J-shaped muscular organ that churns ingested food with hydrochloric acid and pepsin into liquid chyme.",
        location: "Upper left quadrant of abdominal cavity.",
        functions: ["Acidic denaturation of proteins", "Mechanical churning", "Intrinsic factor secretion"],
        additionalFacts: "Gastric juice pH ranges from 1.5 to 2.0 — acidic enough to dissolve mild metals.",
        color: "#E74C3C",
      },
      {
        name: "Liver",
        biologicalTerm: "Hepar",
        description: "The body's chemical refinery; manufactures bile, metabolizes toxins, and stores glycogen.",
        location: "Upper right quadrant beneath diaphragm.",
        functions: ["Bile synthesis", "Detoxification of xenobiotics", "Glycogen and vitamin storage"],
        additionalFacts: "The only internal human organ capable of natural cellular regeneration.",
        color: "#8B4513",
      },
      {
        name: "Pancreas",
        biologicalTerm: "Pancreas",
        description: "Dual endocrine-exocrine gland producing bicarbonate, digestive enzymes, and insulin/glucagon hormones.",
        location: "Retroperitoneal space behind the stomach.",
        functions: ["Exocrine enzyme secretion (lipase, amylase, proteases)", "Endocrine glucose regulation (insulin, glucagon)"],
        additionalFacts: "Secretes approximately 1 liter of pancreatic juice every day.",
        color: "#CD853F",
      },
      {
        name: "Small Intestine",
        biologicalTerm: "Intestinum Tenue",
        description: "Long folded tract lined with millions of microvilli where ~90% of all chemical digestion and absorption occurs.",
        location: "Central abdominal cavity.",
        functions: ["Primary site of nutrient and vitamin absorption", "Enzymatic hydrolysis of lipids and sugars"],
        additionalFacts: "Stretches approximately 6 meters (20 feet) in length.",
        color: "#C0392B",
      },
      {
        name: "Large Intestine",
        biologicalTerm: "Intestinum Crassum",
        description: "Final segment of digestive tract that reabsorbs water, compacts waste, and harbors the beneficial gut microbiome.",
        location: "Frames the perimeter of the small intestine.",
        functions: ["Water and electrolyte reabsorption", "Fecal compaction", "Microbial vitamin K synthesis"],
        additionalFacts: "Houses over 100 trillion symbiotic microorganisms constituting the gut microbiome.",
        color: "#A93226",
      },
    ],
    diseases: ["Crohn's Disease", "Peptic Ulcer", "Cirrhosis", "Diabetes Mellitus"],
    funFacts: [
      "The inner absorptive surface area of the small intestine equals the floor space of a studio apartment.",
      "The stomach creates a new layer of protective epithelial mucus every two weeks to prevent digesting itself.",
    ],
    biomimicry: {
      inspiration: "Bioreactors & Chemical Digesters",
      explanation: "Multi-stage enzymatic degradation, micro-ecological gut fermentation, and selective membrane transport inspired waste-to-energy anaerobic digesters and industrial chemical reactors.",
      module: "Biochemical Engineering",
    },
    relatedOrgans: ["liver", "kidney", "heart"],
  },
  {
    name: "Kidney",
    slug: "kidney",
    system: "Urinary System",
    location: "Retroperitoneal against posterior abdominal wall, either side of vertebral column",
    weight: "150 g each",
    color: "#8E44AD",
    shortDesc: "Biological filter units that cleanse 200 liters of blood daily, regulating fluid balance and blood pressure.",
    overview: "The kidneys maintain physiological osmolarity, electrolyte levels, and systemic acid-base equilibrium while eliminating metabolic waste.",
    description: "Filters waste products and excess water from the blood to produce urine.",
    parts: [
      {
        name: "Cortex",
        biologicalTerm: "Cortex Renis",
        description: "Outer renal layer containing millions of glomeruli and convoluted tubules where filtration begins.",
        location: "Outer peripheral layer of the kidney.",
        functions: ["Primary blood ultrafiltration", "Erythropoietin (EPO) synthesis for RBC production"],
        additionalFacts: "Receives over 90% of all blood flowing into the renal system.",
        color: "#9B59B6",
      },
      {
        name: "Medulla",
        biologicalTerm: "Medulla Renis",
        description: "Inner renal layer composed of 8 to 18 striated renal pyramids that concentrate urine.",
        location: "Deep interior portion of the kidney.",
        functions: ["Countercurrent multiplication of solutes", "Hyperosmotic concentration of urine"],
        additionalFacts: "Contains the hairpin Loops of Henle and terminal collecting ducts.",
        color: "#8E44AD",
      },
      {
        name: "Nephron",
        biologicalTerm: "Nephronum",
        description: "The microscopic structural and functional filtering unit of the kidney.",
        location: "Distributed across cortex and medullary pyramids.",
        functions: ["Glomerular filtration", "Tubular reabsorption of glucose and water", "Tubular secretion of toxins"],
        additionalFacts: "Each healthy human kidney contains roughly 1 million individual nephrons.",
        color: "#6C3483",
      },
      {
        name: "Renal Artery",
        biologicalTerm: "Arteria Renalis",
        description: "High-pressure arterial branch from abdominal aorta delivering unfiltered systemic blood directly to the kidney.",
        location: "Enters through the renal hilum.",
        functions: ["Supplies oxygenated, unfiltered blood to kidneys for purification"],
        additionalFacts: "Delivers approximately 20% to 25% of total resting cardiac output.",
        color: "#5B2C6F",
      },
      {
        name: "Renal Vein",
        biologicalTerm: "Vena Renalis",
        description: "Large venous vessel that drains purified, waste-cleared blood from the kidney back to the inferior vena cava.",
        location: "Exits from renal hilum to inferior vena cava.",
        functions: ["Returns purified deoxygenated blood back to systemic venous circulation"],
        additionalFacts: "Transports blood with the lowest urea and nitrogenous waste concentration in the human body.",
        color: "#D7BDE2",
      },
    ],
    diseases: ["Kidney Stones", "Chronic Kidney Disease", "Kidney Failure"],
    funFacts: [
      "Your kidneys filter your entire circulating blood volume approximately 40 times every 24 hours.",
      "A person can live a completely normal, healthy life with only one functional kidney.",
    ],
    biomimicry: {
      inspiration: "Dialysis Machines & Reverse Osmosis Filters",
      explanation: "Selective semi-permeable membrane transport and countercurrent concentration gradients directly inspired hemodialysis equipment and municipal desalination plants.",
      module: "Filtration Systems",
    },
    relatedOrgans: ["heart", "liver", "lungs"],
  },
  {
    name: "Skeletal System",
    slug: "skeletal-system",
    system: "Skeletal System",
    location: "Throughout the entire human body",
    weight: "~10 kg in average adult",
    color: "#F39C12",
    shortDesc: "The architectural framework of 206 bones that protects vital organs, houses marrow, and enables movement.",
    overview: "The skeleton provides structural rigidity, protects delicate viscera, acts as mechanical levers for locomotion, and houses hematopoiesis.",
    description: "The bodily system of bones and connective tissues providing structure and protection.",
    parts: [
      {
        name: "Skull",
        biologicalTerm: "Cranium",
        description: "Rigid bony protective vault enclosing the encephalon and anchoring facial musculature.",
        location: "Head region.",
        functions: ["Shields delicate brain tissues from blunt trauma", "Supports sensory organs (eyes, ears, olfactory)", "Facilitates chewing"],
        additionalFacts: "Formed of 22 bones joined by fibrous immovable cranial sutures.",
        color: "#FAD7A0",
      },
      {
        name: "Spine",
        biologicalTerm: "Columna Vertebralis",
        description: "Segmented flexible vertebral column supporting torso weight while encasing and shielding the spinal cord.",
        location: "Midline of back extending from skull base to pelvis.",
        functions: ["Supports axial load", "Protects the spinal cord", "Enables trunk flexion, extension, and rotation"],
        additionalFacts: "Composed of 33 vertebrae partitioned by shock-absorbing fibrocartilage intervertebral discs.",
        color: "#F8C471",
      },
      {
        name: "Rib Cage",
        biologicalTerm: "Cavea Thoracis",
        description: "Flexible cage of twelve bone pairs enclosing the thoracic cavity, protecting the heart and lungs.",
        location: "Thorax / chest region.",
        functions: ["Protects heart and lungs", "Expands and contracts during pulmonary ventilation"],
        additionalFacts: "Includes 7 true ribs, 3 false ribs, and 2 floating ribs.",
        color: "#F39C12",
      },
      {
        name: "Pelvis",
        biologicalTerm: "Pelvis",
        description: "Heavy basin-shaped ring of fused bones connecting the vertebral column to lower extremities.",
        location: "Lower trunk at base of spine.",
        functions: ["Transfers weight from upper body to legs", "Shields internal pelvic organs (bladder, reproductive)"],
        additionalFacts: "Displays distinct sexual dimorphism with wider angles in biological females for childbirth.",
        color: "#E67E22",
      },
      {
        name: "Arm Bones",
        biologicalTerm: "Ossa Membri Superioris",
        description: "Appendicular skeletal bones (humerus, radius, ulna, carpals) allowing extraordinary dexterity and range of motion.",
        location: "Upper limbs.",
        functions: ["Enables lifting, manipulation, throwing, and fine tool usage"],
        additionalFacts: "The humerus articulates with the glenoid cavity in the most mobile joint of the human body.",
        color: "#D35400",
      },
      {
        name: "Leg Bones",
        biologicalTerm: "Ossa Membri Inferioris",
        description: "Heavy-duty load-bearing bones (femur, tibia, fibula, tarsals) adapted for bipedal locomotion and stability.",
        location: "Lower limbs.",
        functions: ["Bear full body weight", "Provide mechanical leverage for walking, running, and jumping"],
        additionalFacts: "The femur (thigh bone) is the longest, heaviest, and strongest bone in the human body.",
        color: "#CA6F1E",
      },
    ],
    diseases: ["Osteoporosis", "Arthritis", "Scoliosis", "Fractures"],
    funFacts: [
      "Babies are born with approximately 270 bones, which gradually fuse into 206 bones by adulthood.",
      "Bone tissue is constantly remodeled; your entire skeleton is effectively renewed every 7 to 10 years.",
    ],
    biomimicry: {
      inspiration: "Architectural Truss Frameworks & Lightweight Composites",
      explanation: "The spongy trabecular architecture of bone (dense outer cortical shell, porous shock-absorbing interior) inspired geodesic domes and aircraft fuselage composites.",
      module: "Structural Mechanics",
    },
    relatedOrgans: ["brain", "heart", "lungs"],
  },
];

const diseases = [
  {
    slug: "alzheimers",
    name: "Alzheimer's Disease",
    affectedOrgans: ["brain"],
    category: "Neurological",
    shortDesc: "Progressive neurodegenerative disorder destroying memory, cognition, and independence.",
    symptoms: ["Memory loss", "Spatial disorientation", "Impaired executive function", "Language difficulties"],
    causes: ["Extracellular beta-amyloid plaques", "Intracellular neurofibrillary tau tangles", "Genetic APOE-e4 alleles"],
    treatment: ["Cholinesterase inhibitors (Donepezil)", "NMDA receptor antagonists (Memantine)", "Cognitive stimulation therapy"],
    stages: ["Preclinical", "Mild Cognitive Impairment", "Moderate Dementia", "Severe Dementia"],
    funFact: "Accounts for approximately 60% to 80% of all clinical dementia diagnoses worldwide.",
  },
  {
    slug: "parkinsons",
    name: "Parkinson's Disease",
    affectedOrgans: ["brain"],
    category: "Neurological",
    shortDesc: "Neurodegenerative movement disorder caused by loss of dopamine-producing neurons in the substantia nigra.",
    symptoms: ["Resting tremor (pill-rolling)", "Bradykinesia (slowness)", "Cogwheel muscular rigidity", "Postural instability"],
    causes: ["Degeneration of dopaminergic neurons", "Lewy body alpha-synuclein protein aggregates"],
    treatment: ["Levodopa-Carbidopa", "Dopamine agonists", "Deep Brain Stimulation (DBS) neurosurgery"],
    stages: ["Unilateral involvement", "Bilateral posture changes", "Impaired balance", "Severe disability"],
    funFact: "First formally classified in 1817 as 'The Shaking Palsy' by British physician James Parkinson.",
  },
  {
    slug: "heart-attack",
    name: "Myocardial Infarction (Heart Attack)",
    affectedOrgans: ["heart"],
    category: "Cardiovascular",
    shortDesc: "Ischemic necrosis of heart muscle caused by acute obstruction of coronary arterial flow.",
    symptoms: ["Crushing substernal chest pressure", "Radiation to left arm or jaw", "Diaphoresis (cold sweats)", "Dyspnea"],
    causes: ["Rupture of vulnerable atherosclerotic plaque with acute thrombus formation in coronary arteries"],
    treatment: ["Percutaneous Coronary Intervention (PCI/stenting)", "Fibrinolytic therapy", "Aspirin, Heparin, and Beta-blockers"],
    stages: ["Hyperacute ischemia", "Acute infarction necrosis", "Subacute healing", "Chronic fibrous remodeling"],
    funFact: "Administering emergency chewable aspirin within minutes can reduce mortality by up to 23%.",
  },
  {
    slug: "asthma",
    name: "Bronchial Asthma",
    affectedOrgans: ["lungs"],
    category: "Respiratory",
    shortDesc: "Chronic inflammatory disorder characterized by bronchial hyper-responsiveness and reversible airway obstruction.",
    symptoms: ["Expiratory wheezing", "Chest tightness", "Shortness of breath", "Nocturnal coughing fits"],
    causes: ["Airway hyper-reactivity triggered by allergens, cold air, exercise, or viral respiratory infections"],
    treatment: ["Inhaled short-acting beta-agonists (Albuterol)", "Inhaled corticosteroids", "Leukotriene receptor antagonists"],
    stages: ["Mild Intermittent", "Mild Persistent", "Moderate Persistent", "Severe Persistent"],
    funFact: "Affects over 260 million people globally, making it one of the most common chronic non-communicable diseases.",
  },
  {
    slug: "diabetes",
    name: "Diabetes Mellitus",
    affectedOrgans: ["digestive-system", "kidney", "heart"],
    category: "Endocrine & Metabolic",
    shortDesc: "Metabolic disorder characterized by chronic hyperglycemia due to insulin deficiency or insulin resistance.",
    symptoms: ["Polyuria (excessive urination)", "Polydipsia (excessive thirst)", "Unexplained weight loss", "Fatigue"],
    causes: ["Type 1: Autoimmune beta-cell destruction. Type 2: Peripheral insulin resistance and progressive secretory defect."],
    treatment: ["Insulin therapy", "Metformin (biguanide)", "SGLT2 inhibitors", "Dietary carbohydrate management"],
    stages: ["Euglycemia", "Impaired Fasting Glucose (Prediabetes)", "Overt Diabetes", "End-Organ Microvascular Complications"],
    funFact: "Ancient Greek physicians diagnosed diabetes by tasting patient urine to detect sweet glucose presence.",
  },
  {
    slug: "kidney-stones",
    name: "Nephrolithiasis (Kidney Stones)",
    affectedOrgans: ["kidney"],
    category: "Urinary",
    shortDesc: "Mineral deposits crystallizing in renal calyces that obstruct urinary flow and cause severe renal colic.",
    symptoms: ["Severe acute flank pain radiating to groin", "Hematuria (blood in urine)", "Nausea and vomiting"],
    causes: ["Supersaturation of urine with calcium oxalate, uric acid, or cystine; dehydration"],
    treatment: ["Hydration & analgesics", "Alpha-blockers (Tamsulosin)", "Extracorporeal Shock Wave Lithotripsy (ESWL)"],
    stages: ["Nucleation", "Crystal growth", "Aggregation", "Pelvic / Ureteral obstruction"],
    funFact: "Archaeologists have discovered kidney stones in Egyptian mummies dating back over 7,000 years.",
  },
  {
    slug: "cirrhosis",
    name: "Hepatic Cirrhosis",
    affectedOrgans: ["digestive-system"],
    category: "Gastrointestinal",
    shortDesc: "Late stage of hepatic fibrosis resulting in diffuse reorganization of normal liver architecture into nodular tissue.",
    symptoms: ["Jaundice (yellow skin/eyes)", "Ascites (abdominal fluid buildup)", "Spider angiomas", "Hepatic encephalopathy"],
    causes: ["Chronic viral hepatitis (B or C)", "Alcohol-related liver disease", "Non-alcoholic steatohepatitis (NASH)"],
    treatment: ["Treating underlying etiology", "Sodium restriction and diuretics", "Lactulose", "Liver transplantation"],
    stages: ["Compensated Cirrhosis", "Decompensated Cirrhosis (development of ascites, variceal bleed, or encephalopathy)"],
    funFact: "Despite extensive damage, if caught early, reducing toxic insult allows liver cells to regenerate functionally.",
  },
  {
    slug: "osteoporosis",
    name: "Osteoporosis",
    affectedOrgans: ["skeletal-system"],
    category: "Musculoskeletal",
    shortDesc: "Systemic skeletal disease characterized by low bone mass and microarchitectural deterioration leading to fragility fractures.",
    symptoms: ["Silent progression until sudden fragility fracture", "Loss of height over time", "Stooped dorsal posture (kyphosis)"],
    causes: ["Osteoclastic resorption outpaces osteoblastic bone formation, accelerated by postmenopausal estrogen decline"],
    treatment: ["Bisphosphonates (Alendronate)", "Denosumab (RANKL inhibitor)", "Calcium & Vitamin D3 supplementation", "Weight-bearing exercise"],
    stages: ["Normal BMD", "Osteopenia (T-score -1.0 to -2.5)", "Osteoporosis (T-score <= -2.5)", "Severe Osteoporosis (with fracture)"],
    funFact: "Affects an estimated 200 million individuals globally, causing more than 8.9 million fractures annually.",
  },
];

const seedDB = async (autoExit = false) => {
  try {
    if (mongoose.connection.readyState !== 1) {
      const mongoUri = process.env.MONGO_URI;
      await mongoose.connect(mongoUri);
    }

    // Clear and re-seed Organ collection
    await Organ.deleteMany({});
    const insertedOrgans = await Organ.insertMany(organs);
    console.log(`✅ Successfully seeded ${insertedOrgans.length} anatomical organs!`);

    // Clear and re-seed Disease collection
    await Disease.deleteMany({});
    const insertedDiseases = await Disease.insertMany(diseases);
    console.log(`✅ Successfully seeded ${insertedDiseases.length} clinical diseases!`);

    console.log("🎉 Database seeding complete!");
    if (autoExit) process.exit(0);
    return true;
  } catch (err) {
    console.error("❌ Seeding error:", err.message);
    if (autoExit) process.exit(1);
    return false;
  }
};

if (require.main === module) {
  seedDB(true);
}

module.exports = { seedDB, organs, diseases };
